version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ms_incidencias
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=ms_incidencias
      - JWT_SECRET=mi-secreto-jwt-super-seguro-para-desarrollo
      - JWT_EXPIRES_IN=1h
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mysql_ms_incidencias
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_incidencias
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
