apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: _app_name_
  namespace: _namespace_
  name: _app_name_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: _app_name_
  template:
    metadata:
      labels:
        app: _app_name_
    spec:
      containers:
      - image: _uri_ecr_/_app_name_:_tag_
        # command: ["/bin/sh","-c"]
        # args: ["java -jar -Duser.timezone='America/Santiago' /home/coopeuch/app/app.jar --spring.config.location=/home/coopeuch/app/application.yml"]
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          httpGet:
            path: /api/v1/health
            port: _port_
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          httpGet:
            path: /api/v1/health
            port: _port_
          timeoutSeconds: 1
        name: _app_name_
        ports:
        - containerPort: _port_
          protocol: TCP
        resources:
          limits:
            cpu: _lcp_
            memory: _lmm_
          requests:
            cpu: _rcp_
            memory: _rmm_
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 100
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /coopeuch/.env
          name: conf-volumen
          subPath: .env
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - secret:
          items:
          - key: .env
            path: .env
          secretName: _app_name_
        name: conf-volumen